apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 710255125651.dkr.ecr.us-east-1.amazonaws.com/flask-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  flask-ap
    k8s-app: flask-app
  name: flask-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5001
  type: LoadBalancer
  selector:
    app: flask-app
